apiVersion: v2
name: kubevirt-cdi
description: Install the Containerized Data Importer

type: application
version: 0.2.0
appVersion: "v1.60.3"

maintainers:
  - name: "cloudymax"
    email: "emax@cloudydev.net"
    url: "https://github.com/cloudymax/"
