---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    eni:
      enabled: true
    k8sServiceHost: 192.168.2.70
    k8sServicePort: 6443
    kubeProxyReplacement: true
    l2announcements:
      enabled: false
    l7Proxy: true
    ingressController:
      enabled: false
      loadbalancerMode: shared
    externalIPs:
      enabled: true
    devices: enp11s0f1np1
    k8sClientRateLimit:
      qps: 5
      burst: 10
    operator:
      replicas: 1
    encryption:
      enabled: false
      type: wireguard
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: basic-policy
spec:
  interfaces:
  - wg0
  - enp11s0f1np1
  externalIPs: true
  loadBalancerIPs: true
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "wireguard"
spec:
  cidrs:
  - cidr: "10.1.0.201/30"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "internal"
spec:
  cidrs:
  - cidr: "192.168.2.150/30"
