---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    # Required for multus
    cni:
      exclusive: false
    # Tells Cilium what the main IP is
    k8sServiceHost: 192.168.2.70
    k8sServicePort: 6443
    externalIPs:
      enabled: true
    devices: 
    - enp11s0f1np1
    - wg0
    - enp6s0
    - br0
    operator:
      replicas: 2
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
