virtualMachine:  
  # -- name of the virtualMachine object
  name: kube-virt-vm0
  # -- namespace to deploy the vm
  namespace: default
  # -- One of 'Always' `RerunOnFailure` `Manual` `Halted`
  runStrategy: "RerunOnFailure"
  # -- Enable vm features
  features:
     kvmEnabled: true
     acpiEnabled: true
     smmEnabled: true
     efiEnabled: true
     autoattachPodInterface: true
     autoattachSerialConsole: true
     autoattachGraphicsDevice: true
  machine:
    # -- QEMU virtual-machine type
    machineType: "q35"
    # -- Pass all CPU features and capabilities to Guest
    # cpuPassthrough: true
    # -- Number of Virtual cores to pass to the Guest 
    vCores: 2
    # -- Pin QEMU process to specific physical cores
    # pinCores: true
    # -- Enable the use of Hyperthreading on Intel CPUs. Disable on AMD CPUs.
    hyperThreadingEnabled: false
    # -- Amount of RAM to pass the the Guest
    memory: 4Gi
    # -- path to the user-data file for use with Cloud-Init
    userDataFile: "user-data.yaml"


disks:
  - name: harddrive
    type: disk
    bus: virtio
    boot-order: 2
    readonly: false
    pvsize: 32G
    pvstorageClass: local-path
    pvaccessMode: ReadWriteOnce
    source: "https://cloud.debian.org/images/cloud/bookworm/daily/latest/debian-12-generic-amd64-daily.qcow2"
  - name: cloudinitvolume
    type: cdrom
    bus: sata
    readonly: true
    boot-order: 1
    pv-enable: false

iso:
  bootFromIso: false 
  isoImage: "https://cdimage.debian.org/debian-cd/current/amd64/iso-dvd/debian-12.0.0-amd64-DVD-1.iso"

service:
  type: NodePort
  # -- port to use with k8s service
  port: 22

cloudinit:
  hostname: scrapmetal
  disable_root: false
  network:
    config: disabled
  wireguard: []
  users:
    - name: admin
      groups: users, admin, docker, sudo, kvm
      sudo: ALL=(ALL) NOPASSWD:ALL
      shell: /bin/bash
      lock_passwd: false
    #  passwd: ${PASSWORD}
      ssh_import_id:
        - gh:cloudymax
      ssh_authorized_keys:
        - id_rsa.pub
  ca_certs: []
  boot_cmd: 
    - apt-get update 
    - apt-get install -y ssh-import-id
  write_as_b64: false
  write_files:
    apt-sources-list:
      path: /etc/apt/sources.list
      permissions: '0644'
      content: apt-sources.list
  package_update: true
  package_upgrade: true
  packages: []
  runcmd: 
    - who -r
