{{- range $reg, $props := .Values.disks }}
{{- if $props.pvsize }}
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ $props.name }}
  namespace: {{ $.Values.virtualMachine.namespace }}
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
spec:
  source:
    http:
      certConfigMap: empty-cert
      url: {{ $props.source }}
  pvc:
    accessModes: 
      - {{ $props.pvaccessMode }}
    resources:
      requests:
        storage: {{ $props.pvsize }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: empty-cert
data:
  ca.pem: ""

