apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.virtualMachine.name }}-service
  namespace: {{ .Values.virtualMachine.namespace }}
  labels:
    metallb-service: {{ .Values.virtualMachine.name }}
spec:
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    metallb-service: {{ .Values.virtualMachine.name }}
