{{ if not .Values.virtualMachinePool.enabled }}
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  generation: 1
  labels:
    kubevirt.io/os: linux
    metallb-service: {{ .Values.virtualMachine.name }}
  namespace: {{ .Values.virtualMachine.namespace }}
  name: {{ .Values.virtualMachine.name }}
spec:
  {{- if eq .Values.virtualMachine.machine.instancetype.enabled true }}
  instancetype:
    name: {{ .Values.virtualMachine.machine.instancetype.name }}
    kind: {{ .Values.virtualMachine.machine.instancetype.kind }}
  {{- end }}
  runStrategy: {{ .Values.virtualMachine.runStrategy }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: {{ .Values.virtualMachine.name }}
        kubevirt-service: {{ .Values.virtualMachine.name }}
        kubevirt-manager.io/managed: "true"
    spec:
      architecture: {{ .Values.virtualMachine.machine.architecture }}
      domain:
        machine:
          type: {{ .Values.virtualMachine.machine.machineType }}
        {{- if eq .Values.virtualMachine.features.clock.enabled true }}
        clock:
          utc: {}
          timer:
            {{- if eq .Values.virtualMachine.features.clock.hpet.enabled true }}
            hpet:
              present: {{ .Values.virtualMachine.features.clock.hpet.present }}
            {{- end }}
            {{- if eq .Values.virtualMachine.features.clock.pit.enabled true }}
            pit:
              tickPolicy: {{ .Values.virtualMachine.features.clock.pit.tickPolicy }}
            {{- end }}
            {{- if eq .Values.virtualMachine.features.clock.rtc.enabled true }}
            rtc:
              tickPolicy: {{ .Values.virtualMachine.features.clock.rtc.tickPolicy }}
            {{- end }}
            {{- if eq .Values.virtualMachine.features.clock.hyperv true }}
            hyperv: {}
            {{- end }}
            {{- if eq .Values.virtualMachine.features.clock.kvm true }}
            kvm: {}
            {{- end }}
        {{- end }}
        features:
          {{- if eq .Values.virtualMachine.features.kvmEnabled true -}}
          {{ "kvm: {}" | nindent 10 }}
          {{- end }}
          {{- if eq .Values.virtualMachine.features.acpiEnabled true -}}
          {{ "acpi: {}" | nindent 10 }}
          {{- end }}
          {{- if eq .Values.virtualMachine.features.smmEnabled true -}}
          {{ "smm:"  | nindent 10 -}}
          {{ "enabled: true"  | nindent 12 }}
          {{- end }}
          {{- if eq .Values.virtualMachine.features.hyperv true }}
          hyperv:
            relaxed: {}
            vapic: {}
            vpindex: {}
            spinlocks:
              spinlocks: 8191
            synic: {}
            synictimer:
              direct: {}
            tlbflush: {}
            frequencies: {}
            reenlightenment: {}
            ipi: {}
            runtime: {}
            reset: {}
          {{- end }}
        cpu:
          {{- if eq .Values.virtualMachine.machine.pinCores true }}
          dedicatedCpuPlacement: true
          {{- end }}
          model: {{ .Values.virtualMachine.machine.cpuModel }}
          {{- if eq .Values.virtualMachine.machine.instancetype.enabled false }}
          sockets: 1
          cores: {{ .Values.virtualMachine.machine.vCores -}}
          {{- if .Values.virtualMachine.machine.hyperThreadingEnabled -}}
          {{- "threads: 2" | nindent 10 -}}
          {{ else }}
          {{- "threads: 1" | nindent 10 -}}
          {{- end }}
          {{- end }}
        firmware:
        {{- if .Values.virtualMachine.features.efiEnabled }}
          bootloader:
            efi:
              secureBoot: {{ .Values.virtualMachine.features.secureBoot }}
        {{- else }}
          bootloader: {}
        {{- end }}
        devices:
          {{- with .Values.virtualMachine.interfaces }}
          interfaces:
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if eq .Values.virtualMachine.machine.instancetype.enabled false }}
          {{- with .Values.virtualMachine.gpus }}
          gpus:
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- end }}
          autoattachPodInterface: {{ .Values.virtualMachine.features.autoattachPodInterface }}
          autoattachSerialConsole: {{ .Values.virtualMachine.features.autoattachSerialConsole }}
          autoattachGraphicsDevice: {{ .Values.virtualMachine.features.autoattachGraphicsDevice }}
          networkInterfaceMultiqueue: {{ .Values.virtualMachine.features.networkInterfaceMultiqueue }}
          rng: {}
          inputs:
          - type: tablet
            bus: virtio
            name: tablet1
          disks:
            {{- range $reg, $props := .Values.disks }}
            {{- if ne "hostDisk" $props.type }}
            {{- if ne "configmap" $props.type }}
            {{- if ne "secret" $props.type }}
          - name: {{ $props.name }}
            {{ $props.type }}:
              bus: {{ $props.bus }}
              {{- if eq $props.readonly true }}
              readonly: {{ $props.readonly }}
              {{- end }}
            bootOrder: {{ $props.bootorder }}
            errorPolicy: {{ $.Values.diskErrorPolicy }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if eq $props.type "configmap" }}
          - name: {{ $props.name }}
            serial: {{ $props.serialNumber }}
            cdrom:
              bus: sata
            {{- end }}
            {{- if eq $props.type "secret" }}
          - name: {{ $props.name }}
            serial: {{ $props.serialNumber }}
            {{- end }}
            {{- end }}
        {{- if eq .Values.virtualMachine.machine.instancetype.enabled false }}
        resources:
          limits:
            memory: {{ .Values.virtualMachine.machine.memory }}
        {{- end }}
      {{- with .Values.virtualMachine.networks }}
      networks:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 0
      priorityClassName: {{ .Values.virtualMachine.machine.priorityClassName }}
      volumes:
        {{- range $reg, $props := .Values.disks }}
        {{- if ne "cloudinitvolume" $props.name }}
        {{- if ne "hostDisk" $props.type }}
        {{- if ne "configmap" $props.type }}
        {{- if ne "secret" $props.type }}
        {{- if not $props.ephemeral }}
        {{- if not $props.image }}
        - name: {{ $props.name }}
          persistentVolumeClaim:
            claimName: {{ $props.name }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if eq "configmap" $props.type }}
        - name: {{ $props.name }}
          configMap:
            name: {{ $props.configMap }}
        {{- end }}
        {{- if eq "secret" $props.type }}
        - name: {{ $props.name }}
          secret:
            secretName: {{ $props.secretName }}
        {{- end }}
        {{- if eq "hostDisk" $props.type }}
        - hostDisk:
            capacity: {{ $props.capacity }}
            path: {{ $props.path }}
            type: {{ $props.type }}
          name: {{ $props.name }}
        {{- end}}
        {{- if $props.image }}
        - containerDisk:
            image: {{ $props.image }}
          name: {{ $props.name }}
        {{- end }}
        {{- if $props.ephemeral }}
        - name: {{ $props.name }}
          ephemeral:
            persistentVolumeClaim:
              claimName: {{ $props.pvc }}
        {{- end }}
        {{- end }}
        {{- if eq .Values.cloudinit.enabled true }}
        - name: cloudinitvolume
          cloudInitNoCloud:
            secretRef:
              name: {{ .Values.cloudinit.secretName }}
        {{- end }}
{{- end }}
