{{ if not .Values.virtualMachinePool.enabled }}
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  generation: 1
  labels:
    kubevirt.io/os: linux
    metallb-service: {{ .Values.virtualMachine.name }}
  namespace: {{ .Values.virtualMachine.namespace }}
  name: {{ .Values.virtualMachine.name }}
spec:
  runStrategy: {{ .Values.virtualMachine.runStrategy }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: {{ .Values.virtualMachine.name }}
        kubevirt-service: {{ .Values.virtualMachine.name }}
    spec:
      domain:
        features:
          {{- if .Values.virtualMachine.features.kvmEnabled -}}
          {{ "kvm: {}" | nindent 10 }}
          {{- end }}
          {{- if .Values.virtualMachine.features.acpiEnabled -}}
          {{ "acpi: {}" | nindent 10 }}
          {{- end }}
          {{- if .Values.virtualMachine.features.smmEnabled -}}
          {{ "smm:"  | nindent 10 -}}
          {{ "enabled: true"  | nindent 12 }}
          {{- end }}
        cpu:
          {{- if .Values.virtualMachine.machine.cpuPassthrough -}}
          {{ "model: host-passthrough" | nindent 10 }}
          {{- end }}
          sockets: 1
          cores: {{ .Values.virtualMachine.machine.vCores -}}
          {{- if .Values.virtualMachine.machine.hyperThreadingEnabled -}}
          {{- "threads: 2" | nindent 10 -}}
          {{ else }}
          {{- "threads: 1" | nindent 10 -}}
          {{- end }}
          dedicatedCpuPlacement: {{ .Values.virtualMachine.machine.pinCores }}
        firmware:
        {{- if .Values.virtualMachine.features.efiEnabled }}
          bootloader:
            efi:
              secureBoot: {{ .Values.virtualMachine.features.secureBoot }}
        {{ else }}
          bootloader: {}
        {{- end }}
        devices:
          {{- with .Values.virtualMachine.gpus }}
          gpus:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          autoattachPodInterface: {{ .Values.virtualMachine.features.autoattachPodInterface }}
          autoattachSerialConsole: {{ .Values.virtualMachine.features.autoattachSerialConsole }}
          autoattachGraphicsDevice: {{ .Values.virtualMachine.features.autoattachGraphicsDevice }}
          inputs:
          - type: tablet
            bus: virtio
            name: tablet1
          disks:
            {{- range $reg, $props := .Values.disks }}
            {{- if ne "hostDisk" $props.type }}
          - name: {{ $props.name }}
            {{ $props.type }}:
              bus: {{ $props.bus }}
              readonly: {{ $props.readonly }}
            bootOrder: {{ $props.bootorder }}
            errorPolicy: {{ $.Values.diskErrorPolicy }}
            {{- end }}
            {{- end }}
          interfaces:
            - bridge: {}
              name: default
        machine:
          type: {{ .Values.virtualMachine.machine.machineType }}
        resources:
          requests:
            memory: {{ .Values.virtualMachine.machine.memory }}
      networks:
      - name: default
        pod: {}
      {{- with .Values.livenessProbe }}
      livenessProbe:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.readinessProbe }}
      readinessProbe:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- range $reg, $props := .Values.disks }}
        {{- if ne "cloudinitvolume" $props.name }}
        {{- if ne "hostDisk" $props.type }}
        {{- if not $props.ephemeral }}
        {{- if not $props.image }}
        - name: {{ $props.name }}
          persistentVolumeClaim:
            claimName: {{ $props.name }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if eq "hostDisk" $props.type }}
        - hostDisk:
            capacity: {{ $props.capacity }}
            path: {{ $props.path }}
            type: {{ $props.type }}
          name: {{ $props.name }}
        {{- end}}
        {{- if $props.image }}
        - containerDisk:
            image: {{ $props.image }}
          name: {{ $props.name }}
        {{- end }}
        {{- if $props.ephemeral }}
        - name: {{ $props.name }}
          ephemeral:
            persistentVolumeClaim:
              claimName: {{ $props.pvc }}
        {{- end }}
        {{- end }}
        {{- if eq .Values.cloudinit.enabled true }}
        - name: cloudinitvolume
          cloudInitNoCloud:
            secretRef:
              name: {{ .Values.cloudinit.secretName }}
        {{- end }}
        {{- end }}
