{{ if .Values.virtualMachinePool.enabled }}
apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  name: {{ .Values.virtualMachine.name }}
  namespace: {{ .Values.virtualMachine.namespace }}
spec:
  replicas: {{ .Values.virtualMachinePool.minReplicas }}
  selector:
    matchLabels:
      kubevirt.io/vmpool: {{ .Values.virtualMachine.name }}
      kubevirt.io/domain: {{ .Values.virtualMachine.name }}
      kubevirt-service: {{ .Values.virtualMachine.name }}
  virtualMachineTemplate:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/vmpool: {{ .Values.virtualMachine.name }}
        kubevirt.io/domain: {{ .Values.virtualMachine.name }}
        kubevirt-service: {{ .Values.virtualMachine.name }}
    spec:
      running: true
      template:
        metadata:
          creationTimestamp: null
          labels:
            kubevirt.io/vmpool: {{ .Values.virtualMachine.name }}
            kubevirt.io/domain: {{ .Values.virtualMachine.name }}
            kubevirt-service: {{ .Values.virtualMachine.name }}
        spec:
          domain:
            features:
              {{- if .Values.virtualMachine.features.kvmEnabled -}}
              {{ "kvm: {}" | nindent 14 }}
              {{- end }}
              {{- if .Values.virtualMachine.features.acpiEnabled -}}
              {{ "acpi: {}" | nindent 14 }}
              {{- end }}
              {{- if .Values.virtualMachine.features.smmEnabled -}}
              {{ "smm:"  | nindent 14 -}}
              {{ "enabled: true"  | nindent 16 }}
              {{- end }}
            cpu:
              {{- if .Values.virtualMachine.machine.cpuPassthrough -}}
              {{ "model: host-passthrough" | nindent 14 }}
              {{- end }}
              sockets: 1
              cores: {{ .Values.virtualMachine.machine.vCores -}}
              {{- if .Values.virtualMachine.machine.hyperThreadingEnabled -}}
              {{- "threads: 2" | nindent 14 -}}
              {{ else }}
              {{- "threads: 1" | nindent 14 -}}
              {{- end }}
            {{- if .Values.virtualMachine.features.efiEnabled -}}
            {{- "firmware:" | nindent 12 -}}
            {{- "bootloader:" |nindent 14 -}}
            {{- "efi: {}" | nindent 16 -}}
            {{- end }}
            devices:
              {{- with .Values.virtualMachine.gpus }}
              gpus:
              {{- toYaml . | nindent 14 }}
              {{- end }}
              autoattachPodInterface: {{ .Values.virtualMachine.features.autoattachPodInterface }}
              autoattachSerialConsole: {{ .Values.virtualMachine.features.autoattachSerialConsole }}
              autoattachGraphicsDevice: {{ .Values.virtualMachine.features.autoattachGraphicsDevice }}
              inputs:
              - type: tablet
                bus: virtio
                name: tablet1
              disks:
                {{- range $reg, $props := .Values.disks }}
                {{- if ne "hostDisk" $props.type }}
              - name: {{ $props.name }}
                {{ $props.type }}:
                  bus: {{ $props.bus }}
                  readonly: {{ $props.readonly }}
                bootOrder: {{ $props.bootorder }}
                {{- end }}
                {{- end }}
            resources:
              limits:
                memory: {{ .Values.virtualMachine.machine.memory }}
          terminationGracePeriodSeconds: 0
          volumes:
            {{- range $reg, $props := .Values.disks }}
            {{- if ne "cloudinitvolume" $props.name }}
            {{- if ne "hostDisk" $props.type }}
            {{- if not $props.ephemeral }}
            {{- if not $props.image }}
            - name: {{ $props.name }}
              persistentVolumeClaim:
                claimName: {{ $props.name }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if eq "hostDisk" $props.type }}
            - hostDisk:
                capacity: {{ $props.capacity }}
                path: {{ $props.path }}
                type: {{ $props.type }}
              name: {{ $props.name }}
            {{- end}}
            {{- if $props.image }}
            - containerDisk:
                image: {{ $props.image }}
              name: {{ $props.name }}
            {{- end }}
            {{- if $props.ephemeral }}
            - name: {{ $props.name }}
              ephemeral:
                persistentVolumeClaim:
                  claimName: {{ $props.pvc }}
            {{- end }}
            {{- end }}
            {{- if eq .Values.cloudinit.enabled true }}
            - name: cloudinitvolume
              cloudInitNoCloud:
                secretRef:
                  name: {{ .Values.cloudinit.secretName }}
            {{- end }}
{{- end }}
