apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  generation: 1
  labels:
    kubevirt.io/os: linux
    metallb-service: {{ .Values.virtualMachine.name }}
  namespace: {{ .Values.virtualMachine.namespace }}
  name: {{ .Values.virtualMachine.name }}
spec:
  runStrategy: {{ .Values.virtualMachine.runStrategy }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: {{ .Values.virtualMachine.name }}
        metallb-service: {{ .Values.virtualMachine.name }}
    spec:
      domain:
        features:
          {{- if .Values.virtualMachine.features.kvmEnabled -}}
          {{ "kvm: {}" | nindent 10 }} 
          {{- end }}
          {{- if .Values.virtualMachine.features.acpiEnabled -}}
          {{ "acpi: {}" | nindent 10 }}
          {{- end }}
          {{- if .Values.virtualMachine.features.smmEnabled -}}
          {{ "smm:"  | nindent 10 -}}
          {{ "enabled: true"  | nindent 12 }}
          {{- end }}
        cpu:
          {{- if .Values.virtualMachine.machine.cpuPassthrough -}}
          {{ "model: host-passthrough" | nindent 10 }}
          {{- end }}
          sockets: 1
          cores: {{ .Values.virtualMachine.machine.vCores -}}
          {{- if .Values.virtualMachine.machine.hyperThreadingEnabled -}}
          {{- "threads: 2" | nindent 10 -}}
          {{ else }}
          {{- "threads: 1" | nindent 10 -}}
          {{- end }}
        {{- if .Values.virtualMachine.features.efiEnabled -}}
        {{- "firmware:" | nindent 8 -}}
        {{- "bootloader:" |nindent 10 -}}
        {{- "efi: {}" | nindent 12 -}}
        {{- end }}
        devices:
          autoattachPodInterface: {{ .Values.virtualMachine.features.autoattachPodInterface }}
          autoattachSerialConsole: {{ .Values.virtualMachine.features.autoattachSerialConsole }}
          autoattachGraphicsDevice: {{ .Values.virtualMachine.features.autoattachGraphicsDevice }}
          inputs:
          - type: tablet
            bus: virtio
            name: tablet1
          disks:
            {{- range $reg, $props := .Values.cloudinit.disks }}
           - name: {{ $props.name }}
             {{ $props.type }}:
               bus: {{ $props.bus }}
               boot-order: {{ $props.permissions }}
               readonly: {{ $props.readonly }}
            {{- end }}
          interfaces:
            - masquerade: {}
              name: default
        machine:
          type: {{ .Values.virtualMachine.machine.machineType }}
        resources:
          limits:
            memory: {{ .Values.virtualMachine.machine.memory }}
      networks:
      - name: default
        pod: {}
      volumes:
        {{- range $reg, $props := .Values.cloudinit.disks }}
        - name: {{ $props.name }}
          persistentVolumeClaim:
            claimName: {{ $props.name }}
        {{- end }}
        - name: cloudinitvolume
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: {{ .Values.cloudinit.hostname }}
              disable_root: {{ .Values.cloudinit.disable_root }}
              {{- with .Values.cloudinit.network }}
              network:
                  {{- toYaml . | nindent 16 }}
              {{- end }}
              users: 
                {{- range $reg, $props := .Values.cloudinit.users }}
                - name: {{ $props.name }}
                  groups: {{ $props.groups }}
                  sudo: {{ $props.sudo }}
                  shell: {{ $props.shell }}
                  lock_passwd: {{ $props.lock_passwd }}
                  ssh_import_id: {{ $props.ssh_import_id }}
                  ssh_authorized_keys: {{ $props.ssh_authorized_keys }}
                {{- end }}
              {{- with .Values.cloudinit.boot_cmd }}
              boot_cmd:
                  {{- toYaml . | nindent 16 }}
              {{- end }}
              write_files:
                {{- if .Values.cloudinit.write_as_b64 }}
                {{- range $reg, $props := .Values.cloudinit.write_files }}
              - path: {{ $props.path }}
                permissions: {{ $props.permissions }}
                content: |
                {{- $.Files.Get $props.content | trim |b64enc | nindent 18 }}
                {{- end }}
                {{- else }}
                {{- range $reg, $props := .Values.cloudinit.write_files }}
              - path: {{ $props.path }}
                permissions: {{ $props.permissions }}
                content: |
                {{- $.Files.Get $props.content | trim |nindent 18 }}
                {{- end }}
              {{- end }}
              package_update: {{ .Values.cloudinit.package_update }}
              package_upgrade: {{ .Values.cloudinit.package_upgrade }}
              {{- with .Values.cloudinit.packages }}
              boot_cmd:
                  {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.cloudinit.runcmd }}
              runcmd:
                  {{- toYaml . | nindent 16 }}
              {{- end }}


              
