apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
maxPods: 150
cpuManagerPolicy: "static"
kubeReserved: "cpu=1"
systemReserved: "cpu=1"
verbosity: 4
cpuManagerReconcilePeriod: "5s"
