apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubevirt-cdi.fullname" . }}
  labels:
    {{- include "kubevirt-cdi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubevirt-cdi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      labels:
        {{- include "kubevirt-cdi.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubevirt-cdi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.port }}
              protocol: {{ .Values.service.protocol }}
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: DEPLOY_CLUSTER_RESOURCES
            value: "true"
          - name: OPERATOR_VERSION
            value: {{ .Chart.AppVersion }}
          - name: CONTROLLER_IMAGE
            value: quay.io/kubevirt/cdi-controller:{{ .Chart.AppVersion }}
          - name: IMPORTER_IMAGE
            value: quay.io/kubevirt/cdi-importer:{{ .Chart.AppVersion }}
          - name: CLONER_IMAGE
            value: quay.io/kubevirt/cdi-cloner:{{ .Chart.AppVersion }}
          - name: APISERVER_IMAGE
            value: quay.io/kubevirt/cdi-apiserver:{{ .Chart.AppVersion }}
          - name: UPLOAD_SERVER_IMAGE
            value: quay.io/kubevirt/cdi-uploadserver:{{ .Chart.AppVersion }}
          - name: UPLOAD_PROXY_IMAGE
            value: quay.io/kubevirt/cdi-uploadproxy:{{ .Chart.AppVersion }}
          - name: VERBOSITY
            value: "1"
          - name: PULL_POLICY
            value: IfNotPresent
          - name: MONITORING_NAMESPACE
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

