---
apiVersion: v1
kind: Service
metadata:
  name: cdi-uploadproxy
  namespace: cdi
  labels:
    cdi.kubevirt.io: "cdi-uploadproxy"

spec:
  type: {{ .Values.uploadProxy.type }}
  ports:
    - port: {{ .Values.uploadProxy.port }}
      targetPort: {{ .Values.uploadProxy.targetPort }}
      protocol: {{ .Values.uploadProxy.protocol }}
  selector:
    cdi.kubevirt.io: cdi-uploadproxy
