---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.hostname }}-cloud-init-job
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: cloud-init
          image: jessebot/onboardme:debian12
          env:
 	  {{- range $reg, $props := .Values.users }}
          {{- if $props.password.existingSecret }}
          - name: {{ upper $props.name }}_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $props.password.existingSecret.name }}
                key: {{ $props.password.existingSecret.key }}
	  {{- end }}
          {{- if $props.password.random }}
          - name: {{ upper $props.name }}_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $props.name }}-password
                key: password
	  {{- end }}
	  {{- end }}
          command:
            - /bin/sleep
            - 3650d
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: userdata
              mountPath: /secrets/user-data.yaml
              subPath: user-data.yaml
      volumes:
        - name: userdata
          configMap:
            name: {{ .Values.hostname }}-userdata
