replicaCount: 1

service:
  type: ClusterIP
  port: 8080
  targetPort: 80
  protocol: TCP
  name: http

prometheusEnabled: false

ingress:
  enabled: false
  className: "nginx"
  hostname: "kubevirt.domain.com"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
