replicaCount: 1

service:
  type: ClusterIP
  port: 8080
  protocol: TCP
  name: http

prometheus:
  enabled: false
  serviceName: "prometheus-prometheus"
  serviceNamesapce: "prometheus"

ingress:
  enabled: false
  className: "nginx"
  hostname: "kubevirt.example.com"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  tls:
    enabled: false
    secretName: "tls-kubevirt-manager"
