# Downward API labels and annotations are mounted as a volume
# To get the multus IP, run:
# cat /etc/podinfo/annotations |grep k8s.v1.cni.cncf.io/network-status |sed 's/=/: /g' |yq '."k8s.v1.cni.cncf.io/network-status"' |yq '.[1].ips[0]'
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: dhcp
spec:
  containers:
    - name: samplepod
      command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
      image: ubuntu
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
