# /etc/rancher/k3s/config.yaml
# /etc/rancher/rke2/config.yaml
---
write-kubeconfig-mode: "0600"
node-label: []
cni:
  - cilium

disable:
  - rke2-ingress-nginx

# Internal Network IP
node-ip: 192.168.2.70
bind-address: 192.168.2.70
node-external-ip: 192.168.2.70
advertise-address: 192.168.2.70
tls-san:
  - 192.168.2.70

# Required for l2 IP Announcement
disable-kube-proxy: true

kubelet-arg:
  - "cpu-manager=true"
  - "cpu-manager-policy=static"
  - "cpu-manager-policy-options=full-pcpus-only=true"
  - "cpu-manager-reconcile-period=0s"
  - "kubelet-reserved=cpu=1"
  - "system-reserved=cpu=1"
