# /etc/rancher/k3s/config.yaml
# /etc/rancher/rke2/config.yaml
---
write-kubeconfig-mode: "0644"
node-label: []
cni:
  - cilium
disable:
  - rke2-canal
# Disable rke2 bundled nginx
# fails with: docker invalid tar header: unknown
  - rke2-ingress-nginx

# Internal Network IP
node-ip: 192.168.2.70

# VPN IP Address
node-external-ip: 10.1.0.248

# Required for l2 IP Announcement
disable-kube-proxy: true

node-label:
- ingress-ready=true

kubelet-arg:
- max_pods=150
- node-ip=192.168.2.70
- cpuManagerPolicy=static
- kube-reserved=cpu=1,memory=2Gi,ephemeral-storage=1Gi
- system-reserved=cpu=1,memory=2Gi,ephemeral-storage=1Gi
