# for use with netplan
network:
  bridges:
    br0:
      dhcp4: no
      dhcp6: no
      interfaces: [enp11s0f1np1]
      addresses: [192.168.2.70/24]
      routes:
        - to: default
          via: 192.168.2.1
      mtu: 1500
      nameservers:
        addresses: [192.168.2.1]
      parameters:
        stp: true
        forward-delay: 4
  ethernets:
    enp11s0f1np1:
      dhcp4: no
      dhcp6: no
  renderer: networkd
  version: 2
