# In Container:
# - creates bridge and network iface w/ IP but cannot reach anything in
# either 192.168.2.0 or 10.43.0.0.
# - net1 IP not accesiable from outside
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-static
  namespace: kubevirt
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "mynet",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "br0",
          "disableContainerInterface": false,
          "macspoofchk": false,
          "hairpinMode": true,
          "mtu": 1500,
          "ipam": {
            "type": "static",
            "addresses": [{
                "address": "192.168.2.100/24",
                "gateway": "192.168.2.1"
              }],
            "routes": [
              { "dst": "0.0.0.0/0" },
              { "dst": "192.168.0.0/16", "gw": "192.168.2.1" }
            ],
            "dns": {
              "nameservers" : ["192.168.2.1"]
            }
           }
        }
      ]
    }'
