apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-dhcp
  namespace: kubevirt
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "mynet",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "br0",
          "disableContainerInterface": false,
          "macspoofchk": false,
          "hairpinMode": true,
          "mtu": 1500,
          "ipam": {
            "type": "dhcp"
           }
        }
      ]
    }'
