apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: dhcp
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "enp11s0f1np1",
      "mode": "bridge",
      "ipam": {
        "type": "dhcp",
         "request": [
           {
             "skipDefault": true,
             "option": "subnet-mask"
           }
         ]
      }
    }'
