# Weird packet loss in ping times of ~4 packets evert 40 sec
# In Container:
# - DNS lookups work on 192.168.2.1 
# - DNS lookups don't work on 10.43.0.10
# - External traffic works on net1 device
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-dhcp
  namespace: default
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "br0",
      "mode": "bridge",
      "ipam": {
        "type": "dhcp",
        "request": [
          {
            "skipDefault": false,
            "option": "subnet-mask"
          }
        ]
      }
    }'
---
# Less but still 10% packet loss...
# Works ins a container, no DNS in a VM when only iface
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-dhcp-2
  namespace: default
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "br0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.2.0/24",
        "rangeStart": "192.168.2.200",
        "rangeEnd": "192.168.2.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.2.1"
      }
    }'
