# Weird packet loss in ping times of ~4 packets evert 40 sec
# In Container:
# - DNS lookups work on 192.168.2.1 
# - DNS lookups don't work on 10.43.0.10
# - External traffic works on net1 device
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-static
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "static-ip",
      "type": "macvlan",
      "master": "br0",
      "linkInContainer": false,
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.2.100/24",
            "gateway": "192.168.2.1"
          }
        ],
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.2.1"
      }
    }'
