# Weird packet loss in ping times of up to 20%
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-dhcp
  namespace: default
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "br0",
      "mode": "bridge",
      "ipam": {
        "type": "dhcp",
        "request": [
          {
            "skipDefault": false,
            "option": "subnet-mask"
          }
        ]
      }
    }'
