apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-dhcp
spec:
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 10.43.0.10
    searches:
      - default.svc.cluster.local
      - svc.cluster.local
      - cluster.local
      - localdomain
    options:
      - name: ndots
        value: "5"
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: debian
    volumeMounts:
      - name: podinfo
        mountPath: /etc/podinfo
  initContainers:
    - name: fixroutes
      image: jrecord/nettools
      imagePullPolicy: IfNotPresent
      env:
        - name: DEV
          value: eth0
      command:
        - '/bin/bash'
        - '-c'
        - ip route add 10.43.0.0/16 via $( ip route | grep -P $DEV\\s | grep default | tr -s ' ' | cut -d ' ' -f 3 ) dev $DEV
      securityContext:
        capabilities:
          add:
          - NET_ADMIN
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
