apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: static-ip
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "static-ip",
      "type": "macvlan",
      "master": "enp11s0f1np1",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.2.100/24",
            "gateway": "192.168.2.1"
          },
          {
            "address": "192.168.2.101/24",
            "gateway": "192.168.2.1"
          },
          {
            "address": "192.168.2.102/24",
            "gateway": "192.168.2.1"
          },
          {
            "address": "192.168.2.103/24",
            "gateway": "192.168.2.1"
          },
        ]
      }
    }'
