{{- if (default .Values.priorityclass.create true) }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: kubevirt-cluster-critical
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubevirt.labels" . | nindent 4 }}
value: {{ .Values.priorityclass.value }}
globalDefault: false
description: "This priority class should be used for core kubevirt components only."
{{ end }}