apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    kubevirt.io: ""
  name: kubevirt-operator
  namespace: kubevirt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubevirt.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubevirt.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
