{{- range $reg, $props := .Values.helmCharts }}
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: {{ $props.name }}
spec:
  clusterSelector:
    matchLabels:
      {{ $props.name }}: enabled
  repoURL: {{ $props.repoUrl }}
  chartName: {{ $props.name }}
  options:
    waitForJobs: {{ $props.options.waitForJobs }}
    wait: {{ $props.options.wait }}
    timeout: {{ $props.options.timeout }}
    install:
      createNamespace: {{ $props.options.createNamespace }}
    {{- with $props.values }}
  valuesTemplate: |
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
