name: Lint & Test Kubevirt CDI

on: 
  workflow_dispatch:
  pull_request:
    paths:
      - 'charts/kubevirt-cdi'
  
permissions:
  contents: read

jobs:
  lint:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Add dependency chart repos
        run: |
          helm repo add kubevirt https://cloudymax.github.io/kubevirt-community-stack
          
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        id: lint
        run: |
          ct lint \
          --target-branch ${{ github.event.repository.default_branch }} \
          --charts charts/kubevirt-cdi
        env:
          changed: true

      - uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: 'latest'

      - name: Install helm deps
        run: |
          kubectl create namespace kubevirt
          kubectl create namespace cdi
          kubectl label namespaces cdi app.kubernetes.io/managed-by=Helm --overwrite=true
          kubectl annotate namespaces cdi meta.helm.sh/release-name=cdi
          kubectl annotate namespaces cdi meta.helm.sh/release-namespace=cdi
          helm install kubevirt kubevirt/kubevirt \
            --namespace kubevirt \
            --wait

      - name: Run chart-testing (install)
        id: install
        run: |
          ct install \
          --target-branch ${{ github.event.repository.default_branch }} \
          --charts charts/kubevirt-cdi \
          --namespace cdi
        env:
          changed: true
